### PR TITLE
Bubble-sort & Bubble_sort_by Project for microverse

### PR DESCRIPTION
**Pull request by dasileker**
### **Bubble-sort & Bubble_sort_by Project for microverse**

_in this project, we worked on ruby_  [](url) with :

- rubocop.yml
- stikler.yml
- github/workflow
- bubble_sort_by.rb

**Description of the project**
> Create a method called #bubble_sort_by which sorts an array by accepting a block. Remember to use yield inside your method definition to accomplish this. The block will have two arguments that represent the two elements of the array that are currently being compared. The block’s return will be similar to the spaceship operator you learned about before: If the result of the block execution is negative, the element on the left is “smaller” than the element on the right. 0 means both elements are equal. A positive result means the left element is greater. Use the block’s return value to sort your array. Test your method with the example below.   
 ``> bubble_sort_by(["hi","hello","hey"]) do |left,right|  ``      
  ``> left.length - right.length``   
  `` > end  ``  
 `` => ["hi", "hey", "hello"] 
  ``

### Show your support

Give a ⭐️ if you like this project!

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO @dasileker  AND @ggotora . GREAT WORK SO FAR YOUR METHODS ARE WORKING. JUST A FEW CHANGES TO BE MADE KINDLY WORK ON THE FOLLOWING :arrow_down: 

- [x] Kindly check your robocop. It has some offenses. Kindly fix all the errors

- [x] Kindly add linter to your repo this is a requirement.

### If you have a question concerning the review kindly reach me via slack on @peterrobert

### HAPPY CODING :computer:

**Comment by dasileker** [comment]
hello,

thank you for the review for the linter I do have a linter file in the Github/workflow: linter.yml && the test.yml

**Comment by peterrobert** [comment]
Yes but you had not enabled it in your repo kindly do that

**Comment by Dandush03** [comment]
# Status: :red_circle: Require Changes :red_circle: 

### Hey Guys!, you did a great job, but I see you're having trouble enabling the linter on GitHub
> check out [this link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)

Once you've enabled your linter configuration and the bottom of your PR look like the example given below submit for a new code review.

Screenshot from 2020-09-08 10-58-36
> In your case, you don't have to have the stylelint showed in the picture above

### Happy Coding :nerd_face: :computer:

**Comment by dasileker** [comment]
it's not about the linters it's about what inside them you can explain more next time

**Comment by dasileker** [comment]
I had to remove the --deployment from the tests.yml

**Review by kubilaycaglayan — APPROVED** [review]
Hello Team :wave: 
Status: Approved :green_circle: 

Amazing Demonstration! Good job! :star: :star: :star: 
Sorry for the issue you have experienced :green_apple: It happens sometimes. Don't let it to get your attention, just go on with full speed please :rocket: 

Have a great learning experience! 🎯
With all my respect... :pray:

**Pull request merged**
